from mbase import package

class mfdrn(package):
    '''Drain package class
    layer_row_column_elevation_cond is a list of 2D arrays. Each array has 5 columns containing
    the layer #, row #, column #, elevation and conductance value of a drn cell.
    Enter a separate array for each stress period. When fewer arrays are supplied than stress periods,
    the drn cells of the last array are repeated.
    No parameters implemented'''
    def __init__(self, model, idrncb = 50, layer_row_column_elevation_cond=None, extension ='drn', unitnumber=21):
        package.__init__(self, model, extension, 'DRN', unitnumber) # Call ancestor's init to set self.parent, extension, name and unit number
        self.heading = '# DRN for MODFLOW, generated by Flopy.'
        self.url = 'drn.htm'
        self.idrncb = idrncb  # 0: no cell by cell terms are written
        self.mxactd, self.layer_row_column_elevation_cond = self.assign_layer_row_column_data(layer_row_column_elevation_cond, 5)
        self.np = 0
        self.parent.add_package(self)
    def __repr__( self ):
        return 'Drain package class'
    def ncells( self):
        # Returns the  maximum number of cells that have drains (developped for MT3DMS SSM package)
        print 'Function must be implemented properly for drn package'
        return 0
    def write_file(self):
        f_drn = open(self.fn_path, 'w')
        f_drn.write('%s\n' % self.heading)
        f_drn.write('%10i%10i\n' % (self.mxactd, self.idrncb))
        self.write_layer_row_column_data(f_drn, self.layer_row_column_elevation_cond)
        f_drn.close()

