from mbase import package

class mfevt(package):
    'Evapotranspiration class'
    def __init__(self, model, extension ='evt', unitnumber=22):
        package.__init__(self, model, extension, 'EVT', unitnumber) # Call ancestor's init to set self.parent, extension, name and unit number
        self.heading = '# EVT for MODFLOW, generated by Flopy.'
        self.url = 'evt.htm'
        self.parent.add_package(self)
    def __repr__( self ):
        return 'Evapotranspiration class'
    def ncells( self):
        # Returns the  maximum number of cells that have evapotranspiration (developped for MT3DMS SSM package)
        print 'Function must be implemented properly for evt package'
        return 0
    def write_file(self):
        f_evt = open(self.fn_path, 'w')
        f_evt.close()

