from mbase import package

class mfriv(package):
    'River class'
    def __init__(self, model, irivcb=0, layer_row_column_Q=None, extension ='riv', unitnumber=18):
        package.__init__(self, model, extension, 'RIV', unitnumber) # Call ancestor's init to set self.parent, extension, name and unit number
        self.heading = '# RIV for MODFLOW, generated by Flopy.'
        self.url = 'riv.htm'
        self.irivcb = irivcb
        self.mxactr = 0
        self.mxactr, self.layer_row_column_Q = self.assign_layer_row_column_data(layer_row_column_Q, 6)
        self.np = 0
        self.parent.add_package(self)
    def __repr__( self ):
        return 'River class'
    def ncells( self):
        # Returns the  maximum number of cells that have river (developped for MT3DMS SSM package)
        print 'Function must be implemented properly for riv package'
        return 0
    def write_file(self):
        f_riv = open(self.fn_path, 'w')
        f_riv.write('%s\n' % self.heading)
        f_riv.write('%10i%10i\n' % (self.mxactr, self.irivcb))
        self.write_layer_row_column_data(f_riv, self.layer_row_column_Q)
        f_riv.close()
