#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Tue Apr 17 23:07:49 2007 from C:\_alf\MOD9_GEOPROC\EARTH_modules\GUI\ReSo_dialog.wxg

import wx
from clsReSo_GUI_frame import clsReSo_GUI_frame

class clsReSo_GUI(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        fram_main = clsReSo_GUI_frame(None, -1, "")
        self.SetTopWindow(fram_main)
        fram_main.Show()
        return 1

# end of class clsReSo_GUI

if __name__ == "__main__":
    appReSoGUI = clsReSo_GUI(0)
    appReSoGUI.MainLoop()