# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Tue Apr 17 23:07:49 2007 from C:\_alf\MOD9_GEOPROC\EARTH_modules\GUI\ReSo_dialog.wxg

import wx
import os
import numpy
import tempfile
from pylab import *
from time import *

import ReSo
import ReSoGraph
import clsAbout

# begin wxGlade: dependencies
# end wxGlade

class clsReSo_GUI_frame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: clsReSo_GUI_frame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.pn_output = wx.Panel(self, -1)
        self.pn_RMSE = wx.Panel(self, -1)
        self.pn_graph = wx.Panel(self, -1)
        self.pn_param = wx.Panel(self, -1)
        self.pn_input = wx.Panel(self, -1)
        
        # Menu Bar
        self.fram_main_menubar = wx.MenuBar()
        self.mnFile = wx.Menu()
        self.mnLoadAll = wx.MenuItem(self.mnFile, 10, "Load &All (folder)", "For fast upload, name your files \"__input.txt\", \"__param.txt\", \"__h.txt\" and \"__s.txt\"", wx.ITEM_NORMAL)
        self.mnFile.AppendItem(self.mnLoadAll)
        self.mnFile.AppendSeparator()
        self.mnLoadInput = wx.MenuItem(self.mnFile, 11, "Load &Input", "", wx.ITEM_NORMAL)
        self.mnFile.AppendItem(self.mnLoadInput)
        self.mnLoadParam = wx.MenuItem(self.mnFile, 12, "Load &Param.", "", wx.ITEM_NORMAL)
        self.mnFile.AppendItem(self.mnLoadParam)
        self.mnLoadhMeas = wx.MenuItem(self.mnFile, 13, "Load [&h] meas.", "", wx.ITEM_NORMAL)
        self.mnFile.AppendItem(self.mnLoadhMeas)
        self.mnLoadSMeas = wx.MenuItem(self.mnFile, 14, "Load [&S] meas.", "", wx.ITEM_NORMAL)
        self.mnFile.AppendItem(self.mnLoadSMeas)
        self.mnFile.AppendSeparator()
        self.mnExit = wx.MenuItem(self.mnFile, 15, "E&xit", "", wx.ITEM_NORMAL)
        self.mnFile.AppendItem(self.mnExit)
        self.fram_main_menubar.Append(self.mnFile, "&File")
        self.mnConfig = wx.Menu()
        mnFormatDate = wx.Menu()
        self.mnDateTrace = wx.MenuItem(mnFormatDate, 211, "YYYY&-MM-DD", "", wx.ITEM_RADIO)
        mnFormatDate.AppendItem(self.mnDateTrace)
        self.mnDateSchlas = wx.MenuItem(mnFormatDate, 212, "YYYY&/MM/DD", "", wx.ITEM_RADIO)
        mnFormatDate.AppendItem(self.mnDateSchlas)
        self.mnConfig.AppendMenu(21, "Format da&te", mnFormatDate, "")
        self.fram_main_menubar.Append(self.mnConfig, "Con&figure")
        self.mnHelp = wx.Menu()
        self.mnHelppdf = wx.MenuItem(self.mnHelp, 31, "Help [&pdf]", "", wx.ITEM_NORMAL)
        self.mnHelp.AppendItem(self.mnHelppdf)
        self.mnHelp.AppendSeparator()
        self.mnAbout = wx.MenuItem(self.mnHelp, 32, "A&bout", "", wx.ITEM_NORMAL)
        self.mnHelp.AppendItem(self.mnAbout)
        self.fram_main_menubar.Append(self.mnHelp, "&Help")
        self.SetMenuBar(self.fram_main_menubar)
        # Menu Bar end
        self.fram_main_statusbar = self.CreateStatusBar(1, 0)
        self.pn_13_copy = wx.Panel(self.pn_input, -1)
        self.lbl_InputMain = wx.StaticText(self.pn_input, -1, " INPUT FILES")
        self.lbl_Input = wx.StaticText(self.pn_input, -1, " Inputs")
        self.txt_OpenInput = wx.TextCtrl(self.pn_input, -1, "__input.txt")
        self.lbl_param = wx.StaticText(self.pn_input, -1, " Param.")
        self.txt_OpenParam = wx.TextCtrl(self.pn_input, -1, "__param.txt")
        self.lbl_hmeas = wx.StaticText(self.pn_input, -1, " hmeas")
        self.txt_Openhmeas = wx.TextCtrl(self.pn_input, -1, "__h.txt")
        self.lbl_Smeas = wx.StaticText(self.pn_input, -1, " Smeas")
        self.txt_OpenSmeas = wx.TextCtrl(self.pn_input, -1, "__s.txt")
        self.pn_13 = wx.Panel(self.pn_param, -1)
        self.lbl_paramMain = wx.StaticText(self.pn_param, -1, " PARAMETERS")
        self.panel_1 = wx.Panel(self.pn_param, -1)
        self.panel_2 = wx.Panel(self.pn_param, -1)
        self.pn_02 = wx.Panel(self.pn_param, -1)
        self.pn_03 = wx.Panel(self.pn_param, -1)
        self.pn_04 = wx.Panel(self.pn_param, -1)
        self.lb_SOMOS = wx.StaticText(self.pn_param, -1, "SOMOS", style=wx.ALIGN_CENTRE)
        self.panel_3 = wx.Panel(self.pn_param, -1)
        self.panel_4 = wx.Panel(self.pn_param, -1)
        self.pn_05 = wx.Panel(self.pn_param, -1)
        self.lbl_LINRES = wx.StaticText(self.pn_param, -1, "LINRES", style=wx.ALIGN_CENTRE)
        self.lbl_MAXIL = wx.StaticText(self.pn_param, -1, " MAXIL (mm)")
        self.txt_MAXIL = wx.TextCtrl(self.pn_param, -1, "")
        self.panel_5 = wx.Panel(self.pn_param, -1)
        self.panel_6 = wx.Panel(self.pn_param, -1)
        self.lbl_n = wx.StaticText(self.pn_param, -1, "n")
        self.txt_n = wx.TextCtrl(self.pn_param, -1, "")
        self.lbl_Wm = wx.StaticText(self.pn_param, -1, "Wm (%)")
        self.txt_Wm = wx.TextCtrl(self.pn_param, 150, "")
        self.lbl_Sm = wx.StaticText(self.pn_param, -1, "Sm (mm)")
        self.txt_Sm = wx.TextCtrl(self.pn_param, -1, "")
        self.lbl_f = wx.StaticText(self.pn_param, -1, "f")
        self.txt_f = wx.TextCtrl(self.pn_param, -1, "")
        self.lbl_Wfc = wx.StaticText(self.pn_param, -1, "Wfc (%)")
        self.txt_Wfc = wx.TextCtrl(self.pn_param, 125, "")
        self.lbl_Sfc = wx.StaticText(self.pn_param, -1, "Sfc (mm)")
        self.txt_Sfc = wx.TextCtrl(self.pn_param, -1, "")
        self.pn_06 = wx.Panel(self.pn_param, -1)
        self.lbl_SATFLOW = wx.StaticText(self.pn_param, -1, "SATFLOW", style=wx.ALIGN_CENTRE)
        self.lbl_Wr = wx.StaticText(self.pn_param, -1, "Wr (%)")
        self.txt_Wr = wx.TextCtrl(self.pn_param, 100, "")
        self.lbl_Sr = wx.StaticText(self.pn_param, -1, "Sr (mm)")
        self.txt_Sr = wx.TextCtrl(self.pn_param, -1, "")
        self.lbl_RC = wx.StaticText(self.pn_param, -1, "RC (day)")
        self.txt_RC = wx.TextCtrl(self.pn_param, -1, "")
        self.lbl_Wi = wx.StaticText(self.pn_param, -1, "Wi (%)")
        self.txt_Wi = wx.TextCtrl(self.pn_param, 75, "")
        self.lbl_Si = wx.StaticText(self.pn_param, -1, "Si (mm)")
        self.txt_Si = wx.TextCtrl(self.pn_param, -1, "")
        self.lbl_STO = wx.StaticText(self.pn_param, -1, "STO")
        self.txt_STO = wx.TextCtrl(self.pn_param, -1, "")
        self.lbl_D = wx.StaticText(self.pn_param, -1, "D (mm)")
        self.txt_D = wx.TextCtrl(self.pn_param, 50, "")
        self.panel_7 = wx.Panel(self.pn_param, -1)
        self.panel_8 = wx.Panel(self.pn_param, -1)
        self.lbl_hi = wx.StaticText(self.pn_param, -1, "hi (m)")
        self.txt_hi = wx.TextCtrl(self.pn_param, -1, "")
        self.lbl_Ks = wx.StaticText(self.pn_param, -1, "Ks (mm/day)")
        self.txt_Ks = wx.TextCtrl(self.pn_param, -1, "")
        self.panel_9 = wx.Panel(self.pn_param, -1)
        self.panel_10 = wx.Panel(self.pn_param, -1)
        self.lbl_h0 = wx.StaticText(self.pn_param, -1, "h0 (m)")
        self.txt_h0 = wx.TextCtrl(self.pn_param, -1, "")
        self.lbl_SUSTm = wx.StaticText(self.pn_param, -1, " SUSTm (mm)")
        self.txt_SUSTm = wx.TextCtrl(self.pn_param, -1, "")
        self.panel_11 = wx.Panel(self.pn_param, -1)
        self.pn_07 = wx.Panel(self.pn_param, -1)
        self.lbl_Elev = wx.StaticText(self.pn_param, -1, "Elev. (m)")
        self.txt_Elev = wx.TextCtrl(self.pn_param, -1, "")
        self.bt_hGraph = wx.Button(self.pn_graph, -1, "Piez. calib. graph")
        self.bt_hSGraph = wx.Button(self.pn_graph, -1, "Calibration graphs")
        self.bt_AllGraph = wx.Button(self.pn_graph, -1, "All graphs")
        self.lbl_RMSE_h = wx.StaticText(self.pn_RMSE, -1, "RMSEh")
        self.lbl_RMSE_s = wx.StaticText(self.pn_RMSE, -1, "RMSEs")
        self.lbl_Rtotal = wx.StaticText(self.pn_RMSE, -1, "Rtotal (mm)")
        self.lbl_RFtotal = wx.StaticText(self.pn_RMSE, -1, "RFtotal (mm)")
        self.lbl_Rpercent = wx.StaticText(self.pn_RMSE, -1, "Rtotal (%)")
        self.txt_RMSE_h = wx.TextCtrl(self.pn_RMSE, -1, "")
        self.txt_RMSE_s = wx.TextCtrl(self.pn_RMSE, -1, "")
        self.txt_Rtotal = wx.TextCtrl(self.pn_RMSE, -1, "")
        self.txt_RFtotal = wx.TextCtrl(self.pn_RMSE, -1, "")
        self.txt_Rpercent = wx.TextCtrl(self.pn_RMSE, -1, "")
        self.bt_SaveOutput = wx.Button(self.pn_output, 5, "Export output")
        self.txt_Output = wx.TextCtrl(self.pn_output, -1, "")
        self.bt_SaveParam = wx.Button(self.pn_output, 6, "Export param.")
        self.txt_SaveParam = wx.TextCtrl(self.pn_output, -1, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade



##=========== EVENT MENU ==============##

        self.Bind(wx.EVT_MENU, self.dgOpenFolder, self.mnLoadAll)
        self.Bind(wx.EVT_MENU, self.dgOpenFile, self.mnLoadInput)
        self.Bind(wx.EVT_MENU, self.dgOpenFile, self.mnLoadParam)
        self.Bind(wx.EVT_MENU, self.dgOpenFile, self.mnLoadhMeas)
        self.Bind(wx.EVT_MENU, self.dgOpenFile, self.mnLoadSMeas)
        self.Bind(wx.EVT_MENU, self.Exit, self.mnExit)
        self.Bind(wx.EVT_MENU, self.CallAbout, self.mnAbout)
        self.Bind(wx.EVT_MENU, self.dgDate, self.mnDateSchlas)

##=========== END OF EVENT MENU ==============##

##=========== EVENT BUTTON ==============##

        self.Bind(wx.EVT_BUTTON, self.CallAllGraph, self.bt_AllGraph)
        self.Bind(wx.EVT_BUTTON, self.CallCalibGraph, self.bt_hSGraph)
        self.Bind(wx.EVT_BUTTON, self.CallPiezoCalibGraph, self.bt_hGraph)

        self.Bind(wx.EVT_BUTTON, self.SaveOutput, self.bt_SaveOutput)
        self.Bind(wx.EVT_BUTTON, self.SaveParam, self.bt_SaveParam)

##=========== END OF EVENT BUTTON ==============##

##=========== EVENT TXT ==============##

        self.Bind(wx.EVT_TEXT, self.actualizeS, self.txt_D)
        self.Bind(wx.EVT_TEXT, self.actualizeS, self.txt_Wm)
        self.Bind(wx.EVT_TEXT, self.actualizeS, self.txt_Wfc)
        self.Bind(wx.EVT_TEXT, self.actualizeS, self.txt_Wr)
        self.Bind(wx.EVT_TEXT, self.actualizeS, self.txt_Wi)

##=========== END OF EVENT TXT ==============##

    def __set_properties(self):
        _icon = wx.EmptyIcon()
        path = os.path.dirname(ReSo.__file__)
        _icon.CopyFromBitmap(wx.Bitmap(path + '\\aquaflagged.ico', wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        # begin wxGlade: clsReSo_GUI_frame.__set_properties
        self.SetTitle("pyEARTH1D - Recharge and Soil moisture modelling")
        self.SetSize((435, 759))
        self.SetBackgroundColour(wx.Colour(50, 153, 204))
        self.fram_main_statusbar.SetStatusWidths([-1])
        # statusbar fields
        fram_main_statusbar_fields = ["------------||||==== RUSSIAN DESIGN Co. ====||||------------"]
        for i in range(len(fram_main_statusbar_fields)):
            self.fram_main_statusbar.SetStatusText(fram_main_statusbar_fields[i], i)
        self.lbl_InputMain.SetMinSize((400, 20))
        self.lbl_InputMain.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.txt_OpenInput.SetMinSize((350, 20))
        self.txt_OpenInput.SetBackgroundColour(wx.Colour(148, 255, 255))
        self.txt_OpenInput.Enable(False)
        self.txt_OpenParam.SetMinSize((350, 20))
        self.txt_OpenParam.SetBackgroundColour(wx.Colour(148, 255, 255))
        self.txt_OpenParam.Enable(False)
        self.txt_Openhmeas.SetMinSize((350, 20))
        self.txt_Openhmeas.SetBackgroundColour(wx.Colour(148, 255, 255))
        self.txt_Openhmeas.Enable(False)
        self.txt_OpenSmeas.SetMinSize((350, 20))
        self.txt_OpenSmeas.SetBackgroundColour(wx.Colour(148, 255, 255))
        self.txt_OpenSmeas.Enable(False)
        self.pn_input.SetMinSize((420,165))
        self.pn_input.SetBackgroundColour(wx.Colour(216, 216, 191))
        self.pn_input.SetForegroundColour(wx.Colour(79, 47, 47))
        self.lbl_paramMain.SetMinSize((-1, 20))
        self.lbl_paramMain.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.lb_SOMOS.SetMinSize((-1,-1))
        self.lb_SOMOS.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.lbl_LINRES.SetMinSize((-1, -1))
        self.lbl_LINRES.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.txt_MAXIL.SetMinSize((75, -1))
        self.txt_MAXIL.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_n.SetMinSize((75, -1))
        self.txt_n.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_Wm.SetMinSize((75, -1))
        self.txt_Wm.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_Sm.SetMinSize((50, -1))
        self.txt_Sm.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_Sm.SetForegroundColour(wx.Colour(192, 192, 192))
        self.txt_Sm.Enable(False)
        self.txt_f.SetMinSize((75, -1))
        self.txt_f.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_Wfc.SetMinSize((75, -1))
        self.txt_Wfc.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_Sfc.SetMinSize((50, -1))
        self.txt_Sfc.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_Sfc.Enable(False)
        self.lbl_SATFLOW.SetMinSize((-1, -1))
        self.lbl_SATFLOW.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.txt_Wr.SetMinSize((75, -1))
        self.txt_Wr.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_Sr.SetMinSize((50, -1))
        self.txt_Sr.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_Sr.Enable(False)
        self.txt_RC.SetMinSize((75, -1))
        self.txt_RC.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_Wi.SetMinSize((75, -1))
        self.txt_Wi.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_Si.SetMinSize((50, -1))
        self.txt_Si.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_Si.Enable(False)
        self.txt_STO.SetMinSize((75, -1))
        self.txt_STO.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_D.SetMinSize((75, -1))
        self.txt_D.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_hi.SetMinSize((75, -1))
        self.txt_hi.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_Ks.SetMinSize((75, -1))
        self.txt_Ks.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_h0.SetMinSize((75, -1))
        self.txt_h0.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_SUSTm.SetMinSize((75, -1))
        self.txt_SUSTm.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.txt_Elev.SetMinSize((75, -1))
        self.txt_Elev.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.pn_param.SetMinSize((420,260))
        self.pn_param.SetBackgroundColour(wx.Colour(216, 216, 191))
        self.bt_hGraph.SetMinSize((130, -1))
        self.bt_hGraph.SetBackgroundColour(wx.Colour(50, 50, 204))
        self.bt_hGraph.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.bt_hSGraph.SetMinSize((130, -1))
        self.bt_hSGraph.SetBackgroundColour(wx.Colour(50, 50, 204))
        self.bt_hSGraph.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.bt_AllGraph.SetMinSize((130, -1))
        self.bt_AllGraph.SetBackgroundColour(wx.Colour(50, 50, 204))
        self.bt_AllGraph.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.pn_graph.SetMinSize((420, 35))
        self.pn_graph.SetBackgroundColour(wx.Colour(216, 216, 191))
        self.lbl_RMSE_h.SetMinSize((60, 20))
        self.lbl_RMSE_h.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.lbl_RMSE_s.SetMinSize((60, 20))
        self.lbl_RMSE_s.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.lbl_Rtotal.SetMinSize((85, 20))
        self.lbl_Rtotal.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.lbl_RFtotal.SetMinSize((85, 20))
        self.lbl_RFtotal.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.lbl_Rpercent.SetMinSize((85, 20))
        self.lbl_Rpercent.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.txt_RMSE_h.SetMinSize((60, 20))
        self.txt_RMSE_h.SetBackgroundColour(wx.Colour(148, 255, 255))
        self.txt_RMSE_h.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        self.txt_RMSE_h.Enable(False)
        self.txt_RMSE_s.SetMinSize((60, 20))
        self.txt_RMSE_s.SetBackgroundColour(wx.Colour(148, 255, 255))
        self.txt_RMSE_s.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        self.txt_RMSE_s.Enable(False)        
        self.txt_Rtotal.SetMinSize((75, 20))
        self.txt_Rtotal.SetBackgroundColour(wx.Colour(148, 255, 255))
        self.txt_Rtotal.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        self.txt_Rtotal.Enable(False)
        self.txt_RFtotal.SetMinSize((75, 20))
        self.txt_RFtotal.SetBackgroundColour(wx.Colour(148, 255, 255))
        self.txt_RFtotal.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        self.txt_RFtotal.Enable(False)
        self.txt_Rpercent.SetMinSize((75, 20))
        self.txt_Rpercent.SetBackgroundColour(wx.Colour(148, 255, 255))
        self.txt_Rpercent.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        self.txt_Rpercent.Enable(False)
        self.pn_RMSE.SetMinSize((420,55))
        self.pn_RMSE.SetBackgroundColour(wx.Colour(216, 216, 191))
        self.bt_SaveOutput.SetMinSize((90, -1))
        self.bt_SaveOutput.SetBackgroundColour(wx.Colour(50, 50, 204))
        self.bt_SaveOutput.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.txt_Output.SetMinSize((300, 20))
        self.txt_Output.SetBackgroundColour(wx.Colour(148, 255, 255))
        self.bt_SaveParam.SetMinSize((90, -1))
        self.bt_SaveParam.SetBackgroundColour(wx.Colour(50, 50, 204))
        self.bt_SaveParam.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.txt_SaveParam.SetMinSize((300, 20))
        self.txt_SaveParam.SetBackgroundColour(wx.Colour(148, 255, 255))
        self.pn_output.SetMinSize((420,80))
        self.pn_output.SetBackgroundColour(wx.Colour(216, 216, 191))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: clsReSo_GUI_frame.__do_layout
        grdsz_main = wx.FlexGridSizer(5, 1, 5, 5)
        grdsz_output = wx.FlexGridSizer(2, 2, 5, 5)
        grid_RMSE = wx.GridSizer(2, 5, 5, 5)
        grdsz_graph = wx.FlexGridSizer(1, 3, 2, 2)
        grdsz_param = wx.FlexGridSizer(10, 6, 5, 5)
        grdsz_input = wx.FlexGridSizer(5, 2, 5, 5)
        grdsz_input.Add(self.pn_13_copy, 1, wx.EXPAND, 0)
        grdsz_input.Add(self.lbl_InputMain, 0, 0, 0)
        grdsz_input.Add(self.lbl_Input, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_input.Add(self.txt_OpenInput, 0, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_HORIZONTAL, 5)
        grdsz_input.Add(self.lbl_param, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_input.Add(self.txt_OpenParam, 0, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_HORIZONTAL, 5)
        grdsz_input.Add(self.lbl_hmeas, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_input.Add(self.txt_Openhmeas, 0, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_HORIZONTAL, 5)
        grdsz_input.Add(self.lbl_Smeas, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_input.Add(self.txt_OpenSmeas, 0, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_HORIZONTAL, 5)
        self.pn_input.SetSizer(grdsz_input)
        grdsz_main.Add(self.pn_input, 1, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grdsz_param.Add(self.pn_13, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.lbl_paramMain, 0, wx.ALL, 1)
        grdsz_param.Add(self.panel_1, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.panel_2, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.pn_02, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.pn_03, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.pn_04, 1, 0, 0)
        grdsz_param.Add(self.lb_SOMOS, 0, wx.ALIGN_BOTTOM, 0)
        grdsz_param.Add(self.panel_3, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.panel_4, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.pn_05, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.lbl_LINRES, 0, wx.ALIGN_BOTTOM, 0)
        grdsz_param.Add(self.lbl_MAXIL, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_MAXIL, 0, 0, 0)
        grdsz_param.Add(self.panel_5, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.panel_6, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.lbl_n, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_n, 0, 0, 0)
        grdsz_param.Add(self.lbl_Wm, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_Wm, 0, 0, 0)
        grdsz_param.Add(self.lbl_Sm, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_Sm, 0, 0, 0)
        grdsz_param.Add(self.lbl_f, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_f, 0, 0, 0)
        grdsz_param.Add(self.lbl_Wfc, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_Wfc, 0, 0, 0)
        grdsz_param.Add(self.lbl_Sfc, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_Sfc, 0, 0, 0)
        grdsz_param.Add(self.pn_06, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.lbl_SATFLOW, 0, wx.ALIGN_BOTTOM, 0)
        grdsz_param.Add(self.lbl_Wr, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_Wr, 0, 0, 0)
        grdsz_param.Add(self.lbl_Sr, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_Sr, 0, 0, 0)
        grdsz_param.Add(self.lbl_RC, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_RC, 0, 0, 0)
        grdsz_param.Add(self.lbl_Wi, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_Wi, 0, 0, 0)
        grdsz_param.Add(self.lbl_Si, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_Si, 0, 0, 0)
        grdsz_param.Add(self.lbl_STO, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_STO, 0, 0, 0)
        grdsz_param.Add(self.lbl_D, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_D, 0, 0, 0)
        grdsz_param.Add(self.panel_7, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.panel_8, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.lbl_hi, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_hi, 0, 0, 0)
        grdsz_param.Add(self.lbl_Ks, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_Ks, 0, 0, 0)
        grdsz_param.Add(self.panel_9, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.panel_10, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.lbl_h0, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_h0, 0, 0, 0)
        grdsz_param.Add(self.lbl_SUSTm, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        grdsz_param.Add(self.txt_SUSTm, 0, 0, 0)
        grdsz_param.Add(self.panel_11, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.pn_07, 1, wx.EXPAND, 0)
        grdsz_param.Add(self.lbl_Elev, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_HORIZONTAL, 0)
        grdsz_param.Add(self.txt_Elev, 0, 0, 0)
        self.pn_param.SetSizer(grdsz_param)
        grdsz_main.Add(self.pn_param, 1, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grdsz_graph.Add(self.bt_hGraph, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 2)
        grdsz_graph.Add(self.bt_hSGraph, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 2)
        grdsz_graph.Add(self.bt_AllGraph, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 2)
        self.pn_graph.SetSizer(grdsz_graph)
        grdsz_graph.AddGrowableCol(1)
        grdsz_graph.AddGrowableCol(2)
        grdsz_main.Add(self.pn_graph, 1, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_RMSE.Add(self.lbl_RMSE_h, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_RMSE.Add(self.lbl_RMSE_s, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 0)        
        grid_RMSE.Add(self.lbl_Rtotal, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_RMSE.Add(self.lbl_RFtotal, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_RMSE.Add(self.lbl_Rpercent, 0, wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_RMSE.Add(self.txt_RMSE_h, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_RMSE.Add(self.txt_RMSE_s, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_RMSE.Add(self.txt_Rtotal, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_RMSE.Add(self.txt_RFtotal, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_RMSE.Add(self.txt_Rpercent, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.pn_RMSE.SetSizer(grid_RMSE)
        grdsz_main.Add(self.pn_RMSE, 1, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grdsz_output.Add(self.bt_SaveOutput, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grdsz_output.Add(self.txt_Output, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grdsz_output.Add(self.bt_SaveParam, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grdsz_output.Add(self.txt_SaveParam, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        self.pn_output.SetSizer(grdsz_output)
        grdsz_output.AddGrowableRow(0)
        grdsz_output.AddGrowableRow(1)
        grdsz_main.Add(self.pn_output, 1, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        self.SetSizer(grdsz_main)
        self.Layout()
        # end wxGlade

    def dgOpenFile(self, event):

        # Script modified from wxPython2.8 Docs Demos and Tools
        # Create the dialog. In this case the current directory is forced as the starting
        # directory for the dialog, and no default file name is forced. This can easilly
        # be changed in your program.
        #
        # Finally, if the directory is changed in the process of getting files, this
        # dialog is set up to change the current working directory to the path chosen.

        wildcard = "Tab delimited (*.txt)|*.txt|"\
            "Comma delimited (*.csv)|*.csv|" \
            "Space delimited (*.prn)|*.prn|" \
            "Other delimited (*.dat)|*.dat"

        if event.GetId()==11:
            message='Select input file (date, P and PET)'
        elif event.GetId()==12:
             message='Select parameters file'
        elif event.GetId()==13:
             message='Select measured water level (hmeas) file'
        elif event.GetId()==14:
            message='Select measured soil moisture data (Smeas) file'

        dlg = wx.FileDialog(
            self, message,
            defaultDir=os.getcwd(),
            defaultFile="",
            wildcard=wildcard,
            style=wx.OPEN | wx.CHANGE_DIR
            )

        # Show the dialog and retrieve the user response. If it is the OK response,
        # process the data.
        if dlg.ShowModal() == wx.ID_OK:
            # This returns a Python list of files that were selected.
            path = dlg.GetPaths()
            if event.GetId()==11:
                self.txt_OpenInput.Clear()
                self.txt_OpenInput.WriteText(str(path[0]))
            elif event.GetId()==12:
                self.txt_OpenParam.Clear()
                self.txt_OpenParam.WriteText(str(path[0]))
                if os.path.exists(str(path[0])):
                    param_ar=numpy.loadtxt(str(path[0]))
                    # D updated first to allow actualizeS to work properly
                    self.txt_D.Clear()
                    self.txt_D.WriteText(str(param_ar[5,]))
                    self.txt_MAXIL.Clear()
                    self.txt_MAXIL.WriteText(str(param_ar[0,]))
                    self.txt_Wm.Clear()
                    self.txt_Wm.WriteText(str(param_ar[1,]))
                    self.txt_Sm.Clear()
                    self.txt_Sm.WriteText(str(param_ar[1,]*param_ar[5,]))
                    self.txt_Wfc.Clear()
                    self.txt_Wfc.WriteText(str(param_ar[2,]))
                    self.txt_Sfc.Clear()
                    self.txt_Sfc.WriteText(str(param_ar[2,]*param_ar[5,]))
                    self.txt_Wr.Clear()
                    self.txt_Wr.WriteText(str(param_ar[3,]))
                    self.txt_Sr.Clear()
                    self.txt_Sr.WriteText(str(param_ar[3,]*param_ar[5,]))
                    self.txt_Wi.Clear()
                    self.txt_Wi.WriteText(str(param_ar[4,]))
                    self.txt_Si.Clear()
                    self.txt_Si.WriteText(str(param_ar[4,]*param_ar[5,]))
                    self.txt_Ks.Clear()
                    self.txt_Ks.WriteText(str(param_ar[6,]))
                    self.txt_SUSTm.Clear()
                    self.txt_SUSTm.WriteText(str(param_ar[7,]))
                    self.txt_n.Clear()
                    self.txt_n.WriteText(str(param_ar[8,]))
                    self.txt_f.Clear()
                    self.txt_f.WriteText(str(param_ar[9,]))
                    self.txt_RC.Clear()
                    self.txt_RC.WriteText(str(param_ar[10,]))
                    self.txt_STO.Clear()
                    self.txt_STO.WriteText(str(param_ar[11,]))
                    self.txt_hi.Clear()
                    self.txt_hi.WriteText(str(param_ar[12,]))
                    self.txt_h0.Clear()
                    self.txt_h0.WriteText(str(param_ar[13,]))
                    self.txt_SaveParam.Clear()
                    Outparam_path=str(os.path.split(str(path[0]))[0]) + '\\' + str(os.path.split(os.path.splitext(str(path[0]))[0])[1]) + ".txt"
                    self.txt_SaveParam.WriteText(str(Outparam_path))
                    self.txt_Elev.Clear()
                    self.txt_Elev.WriteText(str(param_ar[14,]))
                else:
                    self.callDialog(2)
            elif event.GetId()==13:
                self.txt_Openhmeas.Clear()
                self.txt_Openhmeas.WriteText(str(path[0]))
            elif event.GetId()==14:
                self.txt_OpenSmeas.Clear()
                self.txt_OpenSmeas.WriteText(str(path[0]))
            Out_path=str(os.path.split(str(path[0]))[0]) + "\\_pyEARTH1D_out.txt"
            self.txt_Output.Clear()
            self.txt_Output.WriteText(str(Out_path))

        dlg.Destroy()

    def dgOpenFolder(self, event):

        # read a initialization file that contains the path of the directory that contains the input files for pyEARTH1D
        strInputsDirIni = os.getcwd() + '\\_inputsDir.ini'
        if os.path.exists(strInputsDirIni):
            inputsDirFile =  open(strInputsDirIni, 'r')
            inputsDir = inputsDirFile.readline()
            inputsDirFile.close()
        else:
            inputsDir = tempfile.gettempdir()

        dlg = wx.DirDialog(self, "Choose a directory with the input files:",
                          style=wx.DD_DEFAULT_STYLE, defaultPath = inputsDir
                           #| wx.DD_DIR_MUST_EXIST
                           #| wx.DD_CHANGE_DIR
                           )

        # Show the dialog and retrieve the user response. If it is the OK response,
        # process the data.
        if dlg.ShowModal() == wx.ID_OK:
            # This returns a Python list of files that were selected.
            path = str(dlg.Path)
            # inputs file
            self.txt_OpenInput.Clear()
            pathInput = path + "\\__input.txt"
            if os.path.exists(pathInput):
                self.txt_OpenInput.WriteText(pathInput)
            else:
                self.callDialog(-1)
            # param files
            pathParam = path + "\\__param.txt"
            self.txt_OpenParam.Clear()
            if os.path.exists(pathParam):
                self.txt_OpenParam.WriteText(pathParam)
                param_ar=numpy.loadtxt(pathParam)
                # D updated first to allow actualizeS to work properly
                self.txt_D.Clear()
                self.txt_D.WriteText(str(param_ar[5,]))
                self.txt_MAXIL.Clear()
                self.txt_MAXIL.WriteText(str(param_ar[0,]))
                self.txt_Wm.Clear()
                self.txt_Wm.WriteText(str(param_ar[1,]))
                self.txt_Sm.Clear()
                self.txt_Sm.WriteText(str(param_ar[1,]*param_ar[5,]))
                self.txt_Wfc.Clear()
                self.txt_Wfc.WriteText(str(param_ar[2,]))
                self.txt_Sfc.Clear()
                self.txt_Sfc.WriteText(str(param_ar[2,]*param_ar[5,]))
                self.txt_Wr.Clear()
                self.txt_Wr.WriteText(str(param_ar[3,]))
                self.txt_Sr.Clear()
                self.txt_Sr.WriteText(str(param_ar[3,]*param_ar[5,]))
                self.txt_Wi.Clear()
                self.txt_Wi.WriteText(str(param_ar[4,]))
                self.txt_Si.Clear()
                self.txt_Si.WriteText(str(param_ar[4,]*param_ar[5,]))
                self.txt_Ks.Clear()
                self.txt_Ks.WriteText(str(param_ar[6,]))
                self.txt_SUSTm.Clear()
                self.txt_SUSTm.WriteText(str(param_ar[7,]))
                self.txt_n.Clear()
                self.txt_n.WriteText(str(param_ar[8,]))
                self.txt_f.Clear()
                self.txt_f.WriteText(str(param_ar[9,]))
                self.txt_RC.Clear()
                self.txt_RC.WriteText(str(param_ar[10,]))
                self.txt_STO.Clear()
                self.txt_STO.WriteText(str(param_ar[11,]))
                self.txt_hi.Clear()
                self.txt_hi.WriteText(str(param_ar[12,]))
                self.txt_h0.Clear()
                self.txt_h0.WriteText(str(param_ar[13,]))
                self.txt_SaveParam.Clear()
                Outparam_path=str(os.path.split(str(path[0]))[0]) + '\\' + str(os.path.split(os.path.splitext(str(path[0]))[0])[1]) + ".txt"
                self.txt_SaveParam.WriteText(str(Outparam_path))
                self.txt_Elev.Clear()
                self.txt_Elev.WriteText(str(param_ar[14,]))
            else:
                    self.callDialog(2)
            # hmeas file
            pathhmeas = path + "\\__h.txt"
            self.txt_Openhmeas.Clear()
            if os.path.exists(pathhmeas):
                 self.txt_Openhmeas.WriteText(pathhmeas)
            else:
                self.callDialog(3)
            # smeas file
            pathsmeas = path + "\\__s.txt"
            self.txt_OpenSmeas.Clear()
            if os.path.exists(pathsmeas):
                 self.txt_OpenSmeas.WriteText(pathsmeas)
            else:
                self.callDialog(4)
            # output file
            Out_path= path + "\\_pyEARTH1D_out.txt"
            self.txt_Output.Clear()
            self.txt_Output.WriteText(Out_path)
            # output param
            Out_param= path + "\\_param_out.txt"
            self.txt_SaveParam.Clear()
            self.txt_SaveParam.WriteText(Out_param)
            #save the path of the input directory
            inputsDirFile = open(strInputsDirIni, 'w')
            inputsDirFile.write(path)
            inputsDirFile.close()
        dlg.Destroy()


    def SaveParam(self, event):
        OutParam_path = self.txt_SaveParam.GetValue()
        outFile=open(OutParam_path, 'w')
        outFile.write(self.txt_MAXIL.GetValue() + '\n')
        outFile.write(self.txt_Wm.GetValue() + '\n')
        outFile.write(self.txt_Wfc.GetValue() + '\n')
        outFile.write(self.txt_Wr.GetValue() + '\n')
        outFile.write(self.txt_Wi.GetValue() + '\n')
        outFile.write(self.txt_D.GetValue() + '\n')
        outFile.write(self.txt_Ks.GetValue() + '\n')
        outFile.write(self.txt_SUSTm.GetValue() + '\n')
        outFile.write(self.txt_n.GetValue() + '\n')
        outFile.write(self.txt_f.GetValue() + '\n')
        outFile.write(self.txt_RC.GetValue() + '\n')
        outFile.write(self.txt_STO.GetValue() + '\n')
        outFile.write(self.txt_hi.GetValue() + '\n')
        outFile.write(self.txt_h0.GetValue()+ '\n')
        outFile.write(self.txt_Elev.GetValue()+ '\n')
        outFile.close()

        self.callDialog(1)

    def actualizeS(self, event):

        if event.GetId()==150 and self.txt_Wm.GetValue()!='':
            self.txt_Sm.Clear()
            self.txt_Sm.WriteText(str(float(self.txt_Wm.GetValue())*float(self.txt_D.GetValue())))
        elif event.GetId()==125 and self.txt_Wfc.GetValue()!='':
            self.txt_Sfc.Clear()
            self.txt_Sfc.WriteText(str(float(self.txt_Wfc.GetValue())*float(self.txt_D.GetValue())))
        elif event.GetId()==100 and self.txt_Wr.GetValue()!='':
            self.txt_Sr.Clear()
            self.txt_Sr.WriteText(str(float(self.txt_Wr.GetValue())*float(self.txt_D.GetValue())))
        elif event.GetId()==75 and self.txt_Wi.GetValue()!='':
            self.txt_Si.Clear()
            self.txt_Si.WriteText(str(float(self.txt_Wi.GetValue())*float(self.txt_D.GetValue())))
        elif event.GetId()==50 and self.txt_D.GetValue()!='':
            if self.txt_Wm.GetValue()!='':
                self.txt_Sm.Clear()
                self.txt_Sm.WriteText(str(float(self.txt_Wm.GetValue())*float(self.txt_D.GetValue())))
            if self.txt_Wfc.GetValue()!='':
                self.txt_Sfc.Clear()
                self.txt_Sfc.WriteText(str(float(self.txt_Wfc.GetValue())*float(self.txt_D.GetValue())))
            if self.txt_Wr.GetValue()!='':
                self.txt_Sr.Clear()
                self.txt_Sr.WriteText(str(float(self.txt_Wr.GetValue())*float(self.txt_D.GetValue())))
            if self.txt_Wi.GetValue()!='':
                self.txt_Si.Clear()
                self.txt_Si.WriteText(str(float(self.txt_Wi.GetValue())*float(self.txt_D.GetValue())))

    def CallPiezoCalibGraph(self, event):

        DateInput, P, PET, Pe, SUST, Qs, ETa, S, Rp, R, h, hmeas, Smeas, Sm, Sr, ErrorType = self.CallrunReSo()

        if ErrorType<>999:
            self.callDialog(ErrorType)
        else:
            if type(DateInput)!=int:
                self.UpdateStats(h, hmeas, S, Smeas, R, P)
                ReSoGraph.piezocalibGRAPH(DateInput, h, hmeas, P, Pe)
    #                cls_CalibGraph.calibGRAPH(DateInput, S, h, hmeas, Smeas, Sm, Sr)
            else :
                self.callDialog(10)

        del DateInput, P, PET, Pe, SUST, Qs, ETa, S, Rp, R, h, hmeas, Smeas, Sm, Sr


    def CallCalibGraph(self, event):

        DateInput, P, PET, Pe, SUST, Qs, ETa, S, Rp, R, h, hmeas, Smeas, Sm, Sr, ErrorType = self.CallrunReSo()

        if ErrorType<>999:
            self.callDialog(ErrorType)
        else:
            if type(DateInput)!=int:
                self.UpdateStats(h, hmeas, S, Smeas, R, P)
                ReSoGraph.calibGRAPH(DateInput, P, PET, Pe, ETa, S, R, h, hmeas, Smeas, Sm, Sr)
    #                cls_CalibGraph.calibGRAPH(DateInput, S, h, hmeas, Smeas, Sm, Sr)
            else :
                self.callDialog(10)

        del DateInput, P, PET, Pe, SUST, Qs, ETa, S, Rp, R, h, hmeas, Smeas, Sm, Sr

    def CallAllGraph(self, event):

        DateInput, P, PET, Pe, SUST, Qs, ETa, S, Rp, R, h, hmeas, Smeas, Sm, Sr, ErrorType = self.CallrunReSo()

        if ErrorType<>999:
            self.callDialog(ErrorType)
        else:
            if type(DateInput)!=int:
                self.UpdateStats(h, hmeas, S, Smeas, R, P)
                ReSoGraph.allGRAPH(DateInput, P, PET, Pe, SUST, Qs, ETa, S, Rp, R, h, hmeas, Smeas, Sm, Sr)
            else :
                self.callDialog(10)

        del DateInput, P, PET, Pe, SUST, Qs, ETa, S, Rp, R, h, hmeas, Smeas, Sm, Sr

    def SaveOutput(self, event):

        DateInput, P, PET, Pe, SUST, Qs, ETa, S, Rp, R, h, hmeas, Smeas, Sm, Sr, ErrorType  = self.CallrunReSo()

        if ErrorType<>999:
            self.callDialog(ErrorType)
        else:
            Output_path = self.txt_Output.GetValue()
            if type(DateInput)!=int:
                ReSo.callExportResults(DateInput, P, PET, Pe, SUST, Qs, ETa, S, Rp, R, h, hmeas, Smeas, Output_path)
                self.callDialog(1)
            else :
                self.callDialog(10)

        del DateInput, P, PET, Pe, SUST, Qs, ETa, S, Rp, R, h, hmeas, Smeas, Sm, Sr

    def CallrunReSo(self):
        param=[]
        param.append(self.txt_MAXIL.GetValue())
        param.append(self.txt_Wm.GetValue())
        param.append(self.txt_Wfc.GetValue())
        param.append(self.txt_Wr.GetValue())
        param.append(self.txt_Wi.GetValue())
        param.append(self.txt_Ks.GetValue())
        param.append(self.txt_D.GetValue())
        param.append(self.txt_SUSTm.GetValue())
        param.append(self.txt_n.GetValue())
        param.append(self.txt_f.GetValue())
        param.append(self.txt_RC.GetValue())
        param.append(self.txt_STO.GetValue())
        param.append(self.txt_hi.GetValue())
        param.append(self.txt_h0.GetValue())
        param.append(self.txt_Elev.GetValue())

        input_path = self.txt_OpenInput.GetValue()

        hmeas_path = self.txt_Openhmeas.GetValue()

        Smeas_path= self.txt_OpenSmeas.GetValue()

        strDateFormat=self.DateFormat()

        DateInput, P, PET, Pe, SUST, Qs, ETa, S, Rp, R, h, hmeas, Smeas, ErrorType = ReSo.runReSo(strDateFormat, param, input_path, hmeas_path, Smeas_path)

        return DateInput, P, PET, Pe, SUST, Qs, ETa, S, Rp, R, h, hmeas, Smeas, param[1], param[3], ErrorType

        del DateInput, P, PET, Pe, SUST, Qs, ETa, S, Rp, R, h, hmeas, Smeas, ErrorType

    def callDialog(self, ErrorType):

        if isinstance(ErrorType, str):
            message = 'Undefined error in the input files!\n'
        elif ErrorType==1:
            message='Done!'
        elif ErrorType==0:
            message= 'Soils parameters are not valid!\nThe conditions are (Sm>Sfc>Sr) and (Sm>Si>Sr)!'
        elif ErrorType==2:
            message= "Parameters file doesn't exist, check path and file name!"
        elif ErrorType==3:
            message= "Observed hydraulic head file doesn't exist, check path and file name!"
        elif ErrorType==4:
            message= "Observed soil moisture file doesn't exist, check path and file name!"
        elif ErrorType==10:
            message= "Error in the input dates!"
        elif ErrorType==-1:
            message= "Input file doesn't exist, check path and file name!"
        elif ErrorType==-2:
            message='Error in the input file, check data format!'
        elif ErrorType==-3:
            message='Parameters are not valid, check values!'
        elif ErrorType == 100:
            message = 'Dates are in the wrong format or are not sequencial, check your input file!'
        elif ErrorType == 101:
            message = 'WARNING, hmeas date is before P and PET date,\n data will not be plotted correctly'
        elif ErrorType == 102:
            message = 'WARNING, there is more hmeas data than P and PET data,\n data will not be plotted correctly'
        elif ErrorType == 103:
            message = 'WARNING, Smeas before P and PET,\n data will not be plotted correctly'
        elif ErrorType == 104:
            message = 'WARNING, there is more Smeas data than P and PET data,\n data will not be plotted correctly'
        else:
            message = "Hé bé, ça c'était pas prévu...\nPlease send your dataset to a.p.frances@utwente.nl"

        dlg = wx.MessageDialog(self, message,
                               'pyEARTH1D',
                               wx.OK | wx.ICON_INFORMATION
                               #wx.YES_NO | wx.NO_DEFAULT | wx.CANCEL | wx.ICON_INFORMATION
                               )
        dlg.ShowModal()
        dlg.Destroy()

    def UpdateStats(self, h, hmeas, S, Smeas, R, P):

        def RMSE(x, xmeas):
            SumError=0
            n=0
            for i in range(len(h)):
                if xmeas[i]!=-999:
                    SumError=(x[i]-xmeas[i])*(x[i]-xmeas[i])+SumError
                    n=n+1
            if n>0:
                RMSE = sqrt(SumError/n)
            else:
                RMSE = -999.99
            
            return RMSE
                
        RMSE_h = RMSE(h, hmeas)
        self.txt_RMSE_h.Clear()
        self.txt_RMSE_h.WriteText(str(round(RMSE_h,2)))

        RMSE_s = RMSE(S, Smeas)
        self.txt_RMSE_s.Clear()
        self.txt_RMSE_s.WriteText(str(round(100.0*RMSE_s,1)))
        
        # R total
        Rtotal=0
        for i in range(len(R)):
            Rtotal=R[i]+Rtotal
        self.txt_Rtotal.Clear()
        self.txt_Rtotal.WriteText(str(round(Rtotal,1)))

        # RF total
        RFtotal=0
        for i in range(len(P)):
            RFtotal=P[i]+RFtotal
        self.txt_RFtotal.Clear()
        self.txt_RFtotal.WriteText(str(round(RFtotal,1)))

        # R %
        Rpercent=Rtotal*100/RFtotal
        self.txt_Rpercent.Clear()
        self.txt_Rpercent.WriteText(str(round(Rpercent,1)))

        del RMSE, Rtotal, RFtotal, Rpercent

    def Exit(self, event):
        self.Close(1)

    def DateFormat(self):
        if self.mnDateTrace.IsChecked():
            strDateFormat='-'
        elif self.mnDateSchlas.IsChecked:
            strDateFormat='/'
        return strDateFormat

    def CallAbout(self, event):

        dlg = clsAbout.clsAbout(self)
        dlg.ShowModal()
        dlg.Destroy()

    def dgDate(self, event):

        message = 'This option is still not supported,\nplease change the date as yyyy-mm-dd format'

        dlg = wx.MessageDialog(self, message,
                               'pyEARTH1D',
                               wx.OK | wx.ICON_INFORMATION
                               #wx.YES_NO | wx.NO_DEFAULT | wx.CANCEL | wx.ICON_INFORMATION
                               )
        dlg.ShowModal()
        dlg.Destroy()


# end of class clsReSo_GUI_frame



