#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.6.3 on Tue May 03 14:01:26 2011

import wx
from clsReSo_GUI_frame import clsReSo_GUI_frame

class clsReSo_GUI(wx.App):
    def OnInit(self):
        #wx.InitAllImageHandlers()
        fram_main = clsReSo_GUI_frame(None, -1, "")
        self.SetTopWindow(fram_main)
        fram_main.Show()
        return 1

# end of class clsReSo_GUI

if __name__ == "__main__":
    start_pyEARTH1D = clsReSo_GUI(0)
    start_pyEARTH1D.MainLoop()
